#!/bin/bash

# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What The Fuck You Want
# To Public License, Version 2, as published by Sam Hocevar and 
# reproduced below.
#
# DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE 
# Version 2, December 2004 
#
# Copyright (C) 2004 Sam Hocevar <sam@hocevar.net> 
#
#	Everyone is permitted to copy and distribute verbatim or modified 
#	copies of this license document, and changing it is allowed as long 
#	as the name is changed. 
#
# DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE 
# TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION 
#
#	0. You just DO WHAT THE FUCK YOU WANT TO.

rp(){
	ratpoison -c "$1"
}

hide(){
	printf "Storing current layout to %s\n" "$(pwd)"
	screens=$(ratpoison -c "sdump" | tr -cd , | wc -c)
	rp sfdump > locked_layout
	# For each screen
	for screen in $(seq 0 $screens); do
		# Lock
		rp only
		rp 'select -'
		rp nextscreen
	done
}

unhide(){
	rp "sfrestore $(<locked_layout)"
	rm locked_layout
}

lock(){
	rp 'newkmap locktop'
	rp 'newkmap locked'
	# Configure your unlock sequence here
	rp 'definekey locktop C-space readkey locked'
	rp 'definekey locked space exec rplock unlock'
	rp 'set topkmap locktop'
}

unlock(){
	rp 'set topkmap top'
	rp 'delkmap locktop'
	rp 'delkmap locked'
}

if [ "$1" == "unlock" ]; then
	unlock
	unhide
else
	hide
	lock
fi
